apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: mcp-route
  namespace: converse-llm
spec:
  parentRefs:
    - name: ai-gateway
      namespace: default
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp"

  backendRefs:
    - name: context7
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/mcp"
      securityPolicy:
        apiKey:
          secretRef:
            name: context7-token

    - name: github-mcp
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/mcp"
      securityPolicy:
        apiKey:
          secretRef:
            name: github-mcp-token

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: context7
  namespace: converse-llm
spec:
  endpoints:
    - fqdn:
        hostname: mcp.context7.com
        port: 443

---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: context7-tls
  namespace: converse-llm
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: context7
  validation:
    wellKnownCACertificates: "System"
    hostname: mcp.context7.com

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: github-mcp
  namespace: converse-llm
spec:
  endpoints:
    - fqdn:
        hostname: api.githubcopilot.com
        port: 443

---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: github-mcp-tls
  namespace: converse-llm
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: github-mcp
  validation:
    wellKnownCACertificates: "System"
    hostname: api.githubcopilot.com
